[package]
authors = ["Jonathan Castello <twisolar@gmail.com>"]
name = "rust-telnet"
version = "0.0.1"
edition = "2018"

[dependencies]
byteorder = "1.0"
tokio-io = "0.1"
bytes = "0.4"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
